# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('unsafe_password', models.CharField(max_length=80)),
                ('account_type', models.CharField(choices=[('blackboard', 'blackboard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('student_id', models.IntegerField()),
                ('course', models.ManyToManyField(to='grading.Course')),
            ],
        ),
    ]
