# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('bb_uva', 'Blackboard UvA'), ('bb_vu', 'Blackboard VU')], max_length=20),
        ),
    ]
