# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('verslag', 'Verslag'), ('expvaardigheden', 'Experimentele vaardigheden')], default='verslag', max_length=20),
            preserve_default=False,
        ),
    ]
