# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='grading.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
