# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_auto_20170307_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
