# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_auto_20170310_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
