# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0013_auto_20170312_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='mail_text',
            field=models.TextField(default='foo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='mail_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
