# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0014_auto_20170317_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='mail_text',
            new_name='mail_body',
        ),
        migrations.AddField(
            model_name='assignment',
            name='mail_subject',
            field=models.CharField(default='beoordeling', max_length=100),
            preserve_default=False,
        ),
    ]
