# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0015_auto_20170317_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('assessment', models.FileField(upload_to='')),
                ('mail_is_sent', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together=set([('assignment', 'student')]),
        ),
    ]
