# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0016_auto_20170408_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='mail_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='mail_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
