# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0017_auto_20170408_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
