# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def enroll_students(apps, schema_editor):
    Student = apps.get_model('grading', 'Student')
    Course = apps.get_model('grading', 'Course')
    for course in Course.objects.all():
        for student in Student.objects.filter(course=course):
            course.students.add(student)
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0018_auto_20170409_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_mark', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.Course')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='grading.Enrollment', to='grading.Student'),
        ),
        migrations.RunPython(enroll_students),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
