# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0019_auto_20170418_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
